// <auto-generated />
namespace JinZhou.V2.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class initDB : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(initDB));
        
        string IMigrationMetadata.Id
        {
            get { return "201810200241442_initDB"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
